version: '3'

services:
   geoserver:
      image: cartologic/geoserver:2.15.2
      volumes:
        - "./geoserver-data:/opt/geoserver/data_dir"
      ports:
        - "8080:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3