version: '3'

services:
   geoserver:
      image: registry.carto.site/geoserver:2.16.0
      volumes:
        - "./geoserver_data:/opt/geoserver/data_dir"
      ports:
        - "3456:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3